### Features + Daily Price Alignment

In [1]:
#Packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Data 
df_price = pd.read_csv(r"C:\Users\USER\PycharmProjects\ThesisProject\Data\Price\price_features.csv")
df_news = pd.read_csv(r"C:\Users\USER\PycharmProjects\ThesisProject\Data\News\news_features.csv")
df_ect = pd.read_csv(r"C:\Users\USER\PycharmProjects\ThesisProject\Data\Transcripts\ect_features.csv")

In [3]:
df_price.head(2)

,date,ticker,Adj_Close,Log_Return,Market_Return,excess_return,Excess_Return_Winsor,Target_T1,Target_T3,Target_T5,movement_T1,movement_T3,movement_T5,lag_return_1d_winsor,volatility_5d_winsor
0,2019-01-10,ADSK,136.710007,-0.000439,0.004508,-0.004947,-0.004947,0.000366,-0.011337,-0.016566,1.0,0.0,0.0,0.017342,0.023311
1,2019-01-11,ADSK,136.740005,0.000219,-0.000146,0.000366,0.000366,-0.009389,-0.018200,0.007570,0.0,0.0,1.0,-0.004947,0.013606

In [4]:
df_news.head(2)

,Date,ticker,title_svm_net_sentiment_mean,title_svm_net_sentiment_max,title_svm_net_sentiment_min,title_svm_net_sentiment_std,title_lr_net_sentiment_mean,title_lr_net_sentiment_max,title_lr_net_sentiment_min,title_lr_net_sentiment_std,...,title_lr_net_sentiment_range,title_lr_net_sentiment_weighted_mean,article_svm_net_sentiment_range,article_svm_net_sentiment_weighted_mean,article_lr_net_sentiment_range,article_lr_net_sentiment_weighted_mean,finbert_net_score_range,finbert_net_score_weighted_mean,gpt_net_sentiment_range,gpt_net_sentiment_weighted_mean
0,2019-01-01,INTC,0.117273,0.117273,0.117273,0.000000,0.175341,0.175341,0.175341,0.000000,...,0.000000,0.121537,0.000000,0.081288,0.000000,0.121537,0.000000,0.006563,0.0,0.415888
1,2019-01-02,BX,0.091911,0.258889,0.022539,0.112202,0.069549,0.115367,0.044030,0.031452,...,0.071337,0.111935,0.228233,0.232718,0.164759,0.172992,0.894551,0.242111,0.8,0.563303

In [5]:
df_ect.head(2)

,Date,ticker,txt_svm_net_sentiment_mean,txt_svm_net_sentiment_max,txt_svm_net_sentiment_min,txt_svm_net_sentiment_std,txt_lr_net_sentiment_mean,txt_lr_net_sentiment_max,txt_lr_net_sentiment_min,txt_lr_net_sentiment_std,...,prepared_finbert_net_score_mean,prepared_gpt_net_sentiment_mean,txt_svm_net_sentiment_range,txt_svm_net_sentiment_weighted_mean,txt_lr_net_sentiment_range,txt_lr_net_sentiment_weighted_mean,finbert_net_score_range,finbert_net_score_weighted_mean,gpt_net_sentiment_range,gpt_net_sentiment_weighted_mean
0,2019-05-23,ADSK,0.310168,0.988758,-0.086349,0.327110,0.239845,0.833664,-0.005094,0.202081,...,0.603007,0.6000,1.075107,1.194192,0.838758,0.923439,1.083374,0.845243,1.1,1.401956
1,2019-08-27,ADSK,0.246779,0.987426,-0.743668,0.452694,0.184628,0.764683,-0.254317,0.247422,...,0.204752,0.2625,1.731094,0.950135,1.019000,0.710844,1.846877,0.911261,1.3,1.075530

In [6]:
#Date columns need to be renamed to match accross all the datasets
#For merging both news and transcripts, llm columns need to be renamed
df_news.columns

Index(['Date', 'ticker', 'title_svm_net_sentiment_mean',
       'title_svm_net_sentiment_max', 'title_svm_net_sentiment_min',
       'title_svm_net_sentiment_std', 'title_lr_net_sentiment_mean',
       'title_lr_net_sentiment_max', 'title_lr_net_sentiment_min',
       'title_lr_net_sentiment_std', 'article_svm_net_sentiment_mean',
       'article_svm_net_sentiment_max', 'article_svm_net_sentiment_min',
       'article_svm_net_sentiment_std', 'article_lr_net_sentiment_mean',
       'article_lr_net_sentiment_max', 'article_lr_net_sentiment_min',
       'article_lr_net_sentiment_std', 'finbert_net_score_mean',
       'finbert_net_score_max', 'finbert_net_score_min',
       'finbert_net_score_std', 'gpt_net_sentiment_mean',
       'gpt_net_sentiment_max', 'gpt_net_sentiment_min',
       'gpt_net_sentiment_std', 'Doc_Count', 'title_svm_net_sentiment_range',
       'title_svm_net_sentiment_weighted_mean', 'title_lr_net_sentiment_range',
       'title_lr_net_sentiment_weighted_mean',
       'article_svm_net_sentiment_range',
       'article_svm_net_sentiment_weighted_mean',
       'article_lr_net_sentiment_range',
       'article_lr_net_sentiment_weighted_mean', 'finbert_net_score_range',
       'finbert_net_score_weighted_mean', 'gpt_net_sentiment_range',
       'gpt_net_sentiment_weighted_mean'],
      dtype='str')

In [7]:
df_ect.columns

Index(['Date', 'ticker', 'txt_svm_net_sentiment_mean',
       'txt_svm_net_sentiment_max', 'txt_svm_net_sentiment_min',
       'txt_svm_net_sentiment_std', 'txt_lr_net_sentiment_mean',
       'txt_lr_net_sentiment_max', 'txt_lr_net_sentiment_min',
       'txt_lr_net_sentiment_std', 'finbert_net_score_mean',
       'finbert_net_score_max', 'finbert_net_score_min',
       'finbert_net_score_std', 'gpt_net_sentiment_mean',
       'gpt_net_sentiment_max', 'gpt_net_sentiment_min',
       'gpt_net_sentiment_std', 'Total_Segment_Count',
       'qa_txt_svm_net_sentiment_mean', 'qa_txt_lr_net_sentiment_mean',
       'qa_finbert_net_score_mean', 'qa_gpt_net_sentiment_mean',
       'prepared_txt_svm_net_sentiment_mean',
       'prepared_txt_lr_net_sentiment_mean', 'prepared_finbert_net_score_mean',
       'prepared_gpt_net_sentiment_mean', 'txt_svm_net_sentiment_range',
       'txt_svm_net_sentiment_weighted_mean', 'txt_lr_net_sentiment_range',
       'txt_lr_net_sentiment_weighted_mean', 'finbert_net_score_range',
       'finbert_net_score_weighted_mean', 'gpt_net_sentiment_range',
       'gpt_net_sentiment_weighted_mean'],
      dtype='str')

In [8]:
#News Columns Renaming
news_col_rename = {
    'Date': 'date',
    'finbert_net_score_mean': 'news_finbert_mean',
    'finbert_net_score_max': 'news_finbert_max',
    'finbert_net_score_min': 'news_finbert_min',
    'finbert_net_score_std':'news_finbert_std',
    'finbert_net_score_range':'news_finbert_range',
    'finbert_net_score_weighted_mean': 'news_finbert_weighted_mean',
    
    'gpt_net_sentiment_mean':'news_gpt_mean',
    'gpt_net_sentiment_max':'news_gpt_max',
    'gpt_net_sentiment_min':'news_gpt_min',
    'gpt_net_sentiment_std':'news_gpt_std',
    'gpt_net_sentiment_range':'news_gpt_range',
    'gpt_net_sentiment_weighted_mean':'news_gpt_weighted_mean'
}
df_news.rename(columns=news_col_rename, inplace=True)

In [9]:
#ECT Columns Renaming
ect_col_rename = {
    'Date': 'date',
    'finbert_net_score_mean':'ect_finbert_mean',
    'finbert_net_score_max':'ect_finbert_max',
    'finbert_net_score_min': 'ect_finbert_min',
    'finbert_net_score_std': 'ect_finbert_std',
    'finbert_net_score_range':'ect_finbert_range',
    'finbert_net_score_weighted_mean': 'ect_finbert_weighted_mean',
    
    'gpt_net_sentiment_mean':'ect_gpt_mean',
    'gpt_net_sentiment_max':'ect_gpt_max',
    'gpt_net_sentiment_min':'ect_gpt_min',
    'gpt_net_sentiment_std':'ect_gpt_std',
    'gpt_net_sentiment_range':'ect_gpt_range',
    'gpt_net_sentiment_weighted_mean':'ect_gpt_weighted_mean'
}
df_ect.rename(columns=ect_col_rename,inplace=True)

In [10]:
#Enforcing datatypes
df_price['date'] = pd.to_datetime(df_price['date'])
df_news['date'] = pd.to_datetime(df_news['date'])
df_ect['date'] = pd.to_datetime(df_ect['date'])

df_price['ticker'] = df_price['ticker'].astype(str)
df_news['ticker'] = df_news['ticker'].astype(str)
df_ect['ticker'] = df_ect['ticker'].astype(str)

#Ensuring correct panel sorting order across all datasets
df_price = df_price.sort_values(by='date').reset_index(drop=True)
df_news = df_news.sort_values(by='date').reset_index(drop=True)
df_ect = df_ect.sort_values(by='date').reset_index(drop=True)

#### News Features + Price

In [11]:
#left_on price means the clean trading-day grid for df_price is preserved

merged_news = pd.merge_asof(
    df_price,
    df_news,
    on='date',
    by='ticker',
    direction='backward', #Matches the most recent historical text sentiment to the current trading day
    tolerance=pd.Timedelta(days=3) #Ensures a cap of max 3 days backwards
)

pd.merge_asof perfectly synchronizes irregular, non-synchronous alternative data with a continuous financial timeline without introducing lookahead bias.

In [12]:
merged_news.head(2)

,date,ticker,Adj_Close,Log_Return,Market_Return,excess_return,Excess_Return_Winsor,Target_T1,Target_T3,Target_T5,...,title_lr_net_sentiment_range,title_lr_net_sentiment_weighted_mean,article_svm_net_sentiment_range,article_svm_net_sentiment_weighted_mean,article_lr_net_sentiment_range,article_lr_net_sentiment_weighted_mean,news_finbert_range,news_finbert_weighted_mean,news_gpt_range,news_gpt_weighted_mean
0,2019-01-10,ADSK,136.710007,-0.000439,0.004508,-0.004947,-0.004947,0.000366,-0.011337,-0.016566,...,0.006237,0.080269,0.214417,0.157016,0.084147,0.123065,0.074113,-0.028599,0.0,0.659167
1,2019-01-10,GS,148.746902,-0.002667,0.004508,-0.007175,-0.007175,0.005417,0.016726,0.108244,...,0.027456,0.028508,0.457543,0.408392,0.320776,0.293215,0.479957,0.229627,0.5,0.384514

#### Transcripts Features + Price

In [13]:
merged_ects = pd.merge_asof(
    df_price,
    df_ect,
    on='date',
    by='ticker',
    direction='backward',
    tolerance=pd.Timedelta(days=3) 
)

In [14]:
merged_ects.head(2)

,date,ticker,Adj_Close,Log_Return,Market_Return,excess_return,Excess_Return_Winsor,Target_T1,Target_T3,Target_T5,...,prepared_finbert_net_score_mean,prepared_gpt_net_sentiment_mean,txt_svm_net_sentiment_range,txt_svm_net_sentiment_weighted_mean,txt_lr_net_sentiment_range,txt_lr_net_sentiment_weighted_mean,ect_finbert_range,ect_finbert_weighted_mean,ect_gpt_range,ect_gpt_weighted_mean
0,2019-01-10,ADSK,136.710007,-0.000439,0.004508,-0.004947,-0.004947,0.000366,-0.011337,-0.016566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-01-10,GS,148.746902,-0.002667,0.004508,-0.007175,-0.007175,0.005417,0.016726,0.108244,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Master Combined Dataset (News + Transcripts + Price)

In [15]:
#News 2019 Filter
news_2019 = merged_news[merged_news['date'].dt.year == 2019].reset_index(drop=True)

In [16]:
#ECT 2024 Filter
ect_2024 = merged_ects[merged_ects['date'].dt.year >= 2024].reset_index(drop=True)

In [17]:
#News + Price Dataset Filter for 2020 to 2023 overlap period
df_merged_news = merged_news[
    (merged_news['date'].dt.year >= 2020) & 
    (merged_news['date'].dt.year <= 2023)
].reset_index(drop=True)

In [18]:
#ECT + Price Dataset Filter for 2020 to 2023 overlap period
df_merged_ect = merged_ects[
    (merged_ects['date'].dt.year >= 2020) & 
    (merged_ects['date'].dt.year <= 2023)
].reset_index(drop=True)

In [19]:
#Master Combined Dataset (News + Transcripts + Price) for overlap period (2020-2023)
#Built using the pre-filtered 2020-2023 news dataset to guarantee perfect structural harmony
master_merged = pd.merge_asof(
    df_merged_news, #Filtered news with price for the period 2020-2023
    df_ect, #original ect dataset without price
    on='date', by='ticker', 
    direction='backward', tolerance=pd.Timedelta(days=3)
).reset_index(drop=True)

In [20]:
master_merged.head(2)

,date,ticker,Adj_Close,Log_Return,Market_Return,excess_return,Excess_Return_Winsor,Target_T1,Target_T3,Target_T5,...,prepared_finbert_net_score_mean,prepared_gpt_net_sentiment_mean,txt_svm_net_sentiment_range,txt_svm_net_sentiment_weighted_mean,txt_lr_net_sentiment_range,txt_lr_net_sentiment_weighted_mean,ect_finbert_range,ect_finbert_weighted_mean,ect_gpt_range,ect_gpt_weighted_mean
0,2020-01-02,ADSK,187.830002,0.023541,0.008344,0.015197,0.015197,-0.008367,0.004606,0.016487,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-01-02,BKR,21.526564,-0.000780,0.008344,-0.009124,-0.009124,0.008255,-0.014149,-0.027667,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
master_merged.columns

Index(['date', 'ticker', 'Adj_Close', 'Log_Return', 'Market_Return',
       'excess_return', 'Excess_Return_Winsor', 'Target_T1', 'Target_T3',
       'Target_T5', 'movement_T1', 'movement_T3', 'movement_T5',
       'lag_return_1d_winsor', 'volatility_5d_winsor',
       'title_svm_net_sentiment_mean', 'title_svm_net_sentiment_max',
       'title_svm_net_sentiment_min', 'title_svm_net_sentiment_std',
       'title_lr_net_sentiment_mean', 'title_lr_net_sentiment_max',
       'title_lr_net_sentiment_min', 'title_lr_net_sentiment_std',
       'article_svm_net_sentiment_mean', 'article_svm_net_sentiment_max',
       'article_svm_net_sentiment_min', 'article_svm_net_sentiment_std',
       'article_lr_net_sentiment_mean', 'article_lr_net_sentiment_max',
       'article_lr_net_sentiment_min', 'article_lr_net_sentiment_std',
       'news_finbert_mean', 'news_finbert_max', 'news_finbert_min',
       'news_finbert_std', 'news_gpt_mean', 'news_gpt_max', 'news_gpt_min',
       'news_gpt_std', 'Doc_Count', 'title_svm_net_sentiment_range',
       'title_svm_net_sentiment_weighted_mean', 'title_lr_net_sentiment_range',
       'title_lr_net_sentiment_weighted_mean',
       'article_svm_net_sentiment_range',
       'article_svm_net_sentiment_weighted_mean',
       'article_lr_net_sentiment_range',
       'article_lr_net_sentiment_weighted_mean', 'news_finbert_range',
       'news_finbert_weighted_mean', 'news_gpt_range',
       'news_gpt_weighted_mean', 'txt_svm_net_sentiment_mean',
       'txt_svm_net_sentiment_max', 'txt_svm_net_sentiment_min',
       'txt_svm_net_sentiment_std', 'txt_lr_net_sentiment_mean',
       'txt_lr_net_sentiment_max', 'txt_lr_net_sentiment_min',
       'txt_lr_net_sentiment_std', 'ect_finbert_mean', 'ect_finbert_max',
       'ect_finbert_min', 'ect_finbert_std', 'ect_gpt_mean', 'ect_gpt_max',
       'ect_gpt_min', 'ect_gpt_std', 'Total_Segment_Count',
       'qa_txt_svm_net_sentiment_mean', 'qa_txt_lr_net_sentiment_mean',
       'qa_finbert_net_score_mean', 'qa_gpt_net_sentiment_mean',
       'prepared_txt_svm_net_sentiment_mean',
       'prepared_txt_lr_net_sentiment_mean', 'prepared_finbert_net_score_mean',
       'prepared_gpt_net_sentiment_mean', 'txt_svm_net_sentiment_range',
       'txt_svm_net_sentiment_weighted_mean', 'txt_lr_net_sentiment_range',
       'txt_lr_net_sentiment_weighted_mean', 'ect_finbert_range',
       'ect_finbert_weighted_mean', 'ect_gpt_range', 'ect_gpt_weighted_mean'],
      dtype='str')

In [22]:
#Date Ranges Verification
#News - 2019
news_min = news_2019['date'].min().strftime('%Y-%m-%d')
news_max = news_2019['date'].max().strftime('%Y-%m-%d')
print(f"News 2019 Dataset Range: {news_min} - {news_max}")

#ECT - 2024
news_min = ect_2024['date'].min().strftime('%Y-%m-%d')
news_max = ect_2024['date'].max().strftime('%Y-%m-%d')
print(f"ECT 2024 Dataset Range: {news_min} - {news_max}")

#Combined News + ECT (2020-2023)
comb_min = master_merged['date'].min().strftime('%Y-%m-%d')
comb_max = master_merged['date'].max().strftime('%Y-%m-%d')
print(f"Overlap Dataset Range: {comb_min} - {comb_max}")

News 2019 Dataset Range: 2019-01-10 - 2019-12-31
ECT 2024 Dataset Range: 2024-01-02 - 2024-12-26
Overlap Dataset Range: 2020-01-02 - 2023-12-29

In [23]:
#Length Validation
print(len(master_merged))
print(len(df_merged_news))
print(len(df_merged_ect))

15090
15090
15090

Above confirms that the merged dataset with news and ects has the same lenght as the individual news+price and ect + price for the overlap period 2020-2023.

#### Validation for News + Price Data

In [24]:
#Structural Completeness & Null Row Audits
nan_targets = df_merged_news[['movement_T1', 'movement_T3','movement_T5']].isnull().sum().sum()
assert nan_targets == 0, f"Found {nan_targets} missing horizon targets!"
print("Active horizon targets are 100% complete.")

Active horizon targets are 100% complete.

In [25]:
#Duplicate Coordinate Check
duplicates = df_merged_news.duplicated(subset=['ticker', 'date']).sum()
assert duplicates == 0, f"Detected {duplicates} duplicate panel rows!"
print("Panel index coordinates are unique.")

Panel index coordinates are unique.

In [26]:
#2019 News Data Validation
#Structural Completeness & Null Row Audits
nan_targets = news_2019[['movement_T1', 'movement_T3','movement_T5']].isnull().sum().sum()
assert nan_targets == 0, f"Found {nan_targets} missing horizon targets!"
print("Active horizon targets are 100% complete.")

#Duplicate Coordinate Check
duplicates = news_2019.duplicated(subset=['ticker', 'date']).sum()
assert duplicates == 0, f"Detected {duplicates} duplicate panel rows!"
print("Panel index coordinates are unique.")

Active horizon targets are 100% complete.
Panel index coordinates are unique.

#### Validation for ECT + Price Data

In [27]:
#Structural Completeness & Null Row Audits
nan_targets = df_merged_ect[['movement_T1', 'movement_T3','movement_T5']].isnull().sum().sum()
assert nan_targets == 0, f"Found {nan_targets} missing horizon targets!"
print("Active horizon targets are 100% complete.")

Active horizon targets are 100% complete.

In [28]:
#Duplicate Coordinate Check
duplicates = df_merged_ect.duplicated(subset=['ticker', 'date']).sum()
assert duplicates == 0, f"Detected {duplicates} duplicate panel rows!"
print("Panel index coordinates are unique.")

Panel index coordinates are unique.

In [29]:
#2024 ECT data validation
#Structural Completeness & Null Row Audits
nan_targets = ect_2024[['movement_T1', 'movement_T3','movement_T5']].isnull().sum().sum()
if nan_targets == 0:
    print("Active horizon targets are 100% complete.")
else:
    print(f"Found {nan_targets} missing horizon targets!")

#Duplicate Coordinate Check
duplicates = ect_2024.duplicated(subset=['ticker', 'date']).sum()
assert duplicates == 0, f"Detected {duplicates} duplicate panel rows!"
print("Panel index coordinates are unique.")

Found 135 missing horizon targets!
Panel index coordinates are unique.

### Validation for Combined Data

In [30]:
#Structural Completeness & Null Row Audits
nan_targets = master_merged[['movement_T1', 'movement_T3','movement_T5']].isnull().sum().sum()
assert nan_targets == 0, f"Found {nan_targets} missing horizon targets!"
print("Multi-horizon target vectors are 100% complete.")

Multi-horizon target vectors are 100% complete.

In [31]:
#Duplicate Coordinate Check
duplicates = master_merged.duplicated(subset=['ticker', 'date']).sum()
assert duplicates == 0, f"Detected {duplicates} duplicate panel rows!"
print("Panel index coordinates are unique.")

Panel index coordinates are unique.

In [32]:
#Lookahead Correlation Check
#Ensures the engineered lag returns and rolling volatilities don't perfectly correlate with targets
max_leakage_corr = 0.0
for ticker, group in master_merged.groupby('ticker'):
    if 'lag_return_1d_winsor' in group.columns and 'movement_T1' in group.columns:
        c = abs(group['lag_return_1d_winsor'].corr(group['movement_T1']))
        if not pd.isna(c) and c > max_leakage_corr:
            max_leakage_corr = c

print(f"Information Coefficient: {max_leakage_corr:.4f}")
assert max_leakage_corr < 0.85, "LEAKAGE DETECTED: Lagged structural components correlate perfectly with future vectors!"
print("Pass: Causal information barrier strictly verified.")

Information Coefficient: 0.0643
Pass: Causal information barrier strictly verified.

In [33]:
#Manual Target Tracing - Selects a sample asset and slice out a consecutive trading sequence
sample_ticker = df_price['ticker'].unique()[0]
inspection_window = df_price[df_price['ticker'] == sample_ticker].sort_values('date').head(6).copy()

print(f"TARGET ALIGNMENT FOR: {sample_ticker}")
print(inspection_window[['date', 'Adj_Close', 'excess_return', 'movement_T1', 'movement_T3']])

TARGET ALIGNMENT FOR: ADSK
         date   Adj_Close  excess_return  movement_T1  movement_T3
0  2019-01-10  136.710007      -0.004947          1.0          0.0
15 2019-01-11  136.740005       0.000366          0.0          0.0
34 2019-01-14  134.750000      -0.009389          0.0          0.0
55 2019-01-15  135.880005      -0.002314          0.0          1.0
69 2019-01-16  135.300003      -0.006497          1.0          1.0
82 2019-01-17  136.500000       0.001267          1.0          1.0

This verification confirms that:

1. Lookahead Bias is 100% Avoided: On any specific day, the feature vectors are trying to predict a future state that has not occurred yet. Today's target does not echo today's return.

2. Calendar Continuity Holds: Weekends are handled correctly and there is a seamless jump for example from Friday, Jan 11th to Monday, Jan 14th.

In [34]:
#Reviewing NANs
def profile_merge_loss(df, dataset_name, canary_col):
    total_market_days = len(df)
    
    #Matched rows are those where the text feature successfully populated
    matched_rows = df[canary_col].notnull().sum()
    unmatched_rows = df[canary_col].isnull().sum()
    
    match_percentage = (matched_rows / total_market_days) * 100
    loss_percentage = (unmatched_rows / total_market_days) * 100
    
    print(f"Dataset: {dataset_name}")
    print(f"Total Baseline Market Rows: {total_market_days:,}")
    print(f"Matched Observations: {matched_rows:,} ({match_percentage:.2f}%)")
    print(f"Unmatched Gaps (NaNs): {unmatched_rows:,} ({loss_percentage:.2f}%)")
    return unmatched_rows

In [35]:
#Reviewing the News merged dataset using a sample column
news_loss = profile_merge_loss(
    df=df_merged_news, 
    dataset_name="DAILY NEWS + PRICE (2020-2023)", 
    canary_col="title_svm_net_sentiment_mean"
)

Dataset: DAILY NEWS + PRICE (2020-2023)
Total Baseline Market Rows: 15,090
Matched Observations: 12,989 (86.08%)
Unmatched Gaps (NaNs): 2,101 (13.92%)

In [36]:
#Reviewing the ECT merged dataset using a sample column
ect_loss = profile_merge_loss(
    df=df_merged_ect, 
    dataset_name="ECTs + PRICE (2020-2023)", 
    canary_col="ect_gpt_max"
)

Dataset: ECTs + PRICE (2020-2023)
Total Baseline Market Rows: 15,090
Matched Observations: 627 (4.16%)
Unmatched Gaps (NaNs): 14,463 (95.84%)

Gaps in the ECT dataset will be more considering the data is sparse as earning call transcripts are quarterly events.

In [37]:
#Reviewing the combined dataset using a sample column
comb_loss = profile_merge_loss(
    df=master_merged, 
    dataset_name="COMBINED MULTI-MODAL SUITE (2020-2023)", 
    canary_col="news_finbert_mean"
)

Dataset: COMBINED MULTI-MODAL SUITE (2020-2023)
Total Baseline Market Rows: 15,090
Matched Observations: 12,989 (86.08%)
Unmatched Gaps (NaNs): 2,101 (13.92%)

In [38]:
#Saving Data
output_path1 = r'C:\Users\USER\PycharmProjects\ThesisProject\Data\News\news_2019.csv'
output_path2 = r'C:\Users\USER\PycharmProjects\ThesisProject\Data\Transcripts\ect_2024.csv'
output_path3 = r'C:\Users\USER\PycharmProjects\ThesisProject\Data\News\news_price.csv'
output_path4 = r'C:\Users\USER\PycharmProjects\ThesisProject\Data\Transcripts\ect_price.csv'
output_path5 = r'C:\Users\USER\PycharmProjects\ThesisProject\Data\master_merged.csv'

news_2019.to_csv(output_path1, index=False) #news+price 2019
ect_2024.to_csv(output_path2, index=False) #ect+price 2024
df_merged_news.to_csv(output_path3, index=False) #news+price (2020-2023)
df_merged_ect.to_csv(output_path4, index=False) #ect+price (2020-2023)
master_merged.to_csv(output_path5, index=False) #news+ect+price (2020-2023)
print('Success!')

Success!